name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Install Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      # Run proxy scanner
      - name: Start Scan
        run: |
          bun install && bun run ./vless/proxyip.ts

      # Publish the result
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["./*List.txt", "./*List.json"]'
          fetch: false
          tag_push: "--force"
          message: "Update proxy list"
